import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background: "#0c0c0c",
        }}
        className={`${poppins.className} text-white mx-40`}
      >
          {children}
      </body>
    </html>
  );
}
